author: Flavio Lichtenstein  
data update:   2019/01/26
data created:  2016/07/20  
local: Molecular Biology/Inovation & CENTD - Butantan Institute  

## Lecture 03 - introduction R

**assign a value to a variable**

In [1]:
a <- 1
2 -> b
c = 3

### How to echo here / console

In [7]:
a

[1] 1

In [8]:
a
b

[1] 1

[1] 2

In [11]:
#-- observe: all vars are matrices [1] 

print(a)
print(b)
print(c)

[1] 1
[1] 2
[1] 3


In [18]:
print( a,b,c )

[1] 1


In [19]:
print( c(a,b,c) )

[1] 1 2 3


In [24]:
paste( a,b,c )

[1] "1 2 3"

In [25]:
print( paste(a,b,c) )

[1] "1 2 3"


In [26]:
print( paste(a,b,c, sep = ";" ))

[1] "1;2;3"


In [27]:
cat( paste(a,b,c) )

1 2 3

In [28]:
cat( sprintf("variables are %s, %s and %s.\n", a, b, c))

variables are 1, 2 and 3.


### Mathematical operations

In [32]:
#--- addition
a+b

[1] 3

a+b+c

In [35]:
#-- subtraction
a - b

In [37]:
#-- multiplication
a * b

[1] 2

In [40]:
sprintf("Multiplication a=%d *  b=%d =  %d", a, b, a*b)

[1] "Multiplication a=1 *  b=2 =  2"

In [41]:
#-- division
a / b

[1] 0.5

In [42]:
#-- potentialization
b**2

[1] 4

In [69]:
#-- potentialization
a**b

[1] 9

In [43]:
#--- square root
sqrt(b)

[1] 1.414214

In [44]:
#--- any root
b**(1/2)

[1] 1.414214

In [55]:
#-- mod
print(a %% b)
print(5 %% 2)
print(5 %% 3)

[1] 3
[1] 1
[1] 2


In [56]:
#-- integer division
print(a %/% b)
print(5 %/% 2)
print(5 %/% 3)
print(21 %/% 5)

[1] 0
[1] 2
[1] 1
[1] 4


In [57]:
#--- complex operations 
5 + 2*(a*b*c**2)

[1] 5

In [58]:
#-- exponetialtion
exp(1)

[1] 2.718282

In [59]:
#-- expoente using a var
exp(b)

[1] 54.59815

In [60]:
#-------- rounding ----------------

a = 1/6
b = round(a, 2)
c = round(a)

print(paste(a, class(a)))
print(paste(b, class(b)))
print(paste(c, class(c)))

[1] "0.166666666666667 numeric"
[1] "0.17 numeric"
[1] "0 numeric"


In [61]:
#--- comparings --> result boolean

a = 3
b = 4
c = (a == b)
d = (a != b)

print(paste(a, class(a)))
print(paste(b, class(b)))
print(paste(c, class(c)))
print(paste(d, class(d)))

[1] "3 numeric"
[1] "4 numeric"
[1] "FALSE logical"
[1] "TRUE logical"


### Data types

In [62]:
a = 3
b = 3.5
c = 1/6
d = "a"
e = "abcd"
f = "I saw a bird."

print(paste(a, class(a)))
print(paste(b, class(b)))
print(paste(c, class(c)))
print(paste(d, class(d)))
print(paste(e, class(e)))

sprintf("frase: '%s', type:'%s'",f, class(f))
cat(sprintf("frase: '%s', type:'%s'",f, class(f)))

[1] "3 numeric"
[1] "3.5 numeric"
[1] "0.166666666666667 numeric"
[1] "a character"
[1] "abcd character"


[1] "frase: 'I saw a bird.', type:'character'"

frase: 'I saw a bird.', type:'character'

In [63]:
intToBits(12)

 [1] 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[26] 00 00 00 00 00 00 00

In [64]:
x <- rev(intToBits(12))
x <- paste(as.integer(x), collapse = "")

In [65]:
x = intToBits(12)
class(x)
typeof(x)

[1] "raw"

[1] "raw"

In [67]:
suppressWarnings(library(R.utils))

x = intToBin(12)

print(x)
cat(x)
typeof(x)

[1] "1100"
1100

[1] "character"

### Every variable in R is a vector ou matrix

In [68]:
a
class(a)

[1] 3

[1] "numeric"

In [69]:
v = c(1,2,3)
v

[1] 1 2 3

In [71]:
class(v)
length(v)

[1] "numeric"

[1] 3

In [75]:
v2 = rep("a",3)
v2

[1] "a" "a" "a"

In [76]:
class(v2)
length(v2)

[1] "character"

[1] 3

In [77]:
v3 = seq(1,30,2)
v3

[1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29

In [78]:
class(v3)
length(v3)

[1] "numeric"

[1] 15

### Add and Delete elements in a vector

In [80]:
#-- a simple vector
v = c(1,2,3)
v

[1] 1 2 3

In [81]:
#-- merging - union
v = c(v, c(4,5,6))
v

[1] 1 2 3 4 5 6

In [82]:
v = v[-(2)]
v

[1] 1 3 4 5 6

### Filtering elements in a vector

In [83]:
v[2:3]

[1] 3 4

In [84]:
v[2:]

ERROR: Error in parse(text = x, srcfile = src): <text>:1:5: unexpected ']'
1: v[2:]
        ^


In [85]:
v[2:length(v)]

[1] 3 4 5 6

### Operations in a vector

In [86]:
v = 1:10
v**2

[1]   1   4   9  16  25  36  49  64  81 100

In [87]:
v*5

[1]  5 10 15 20 25 30 35 40 45 50

In [88]:
v/2

[1] 0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

In [89]:
v+3

[1]  4  5  6  7  8  9 10 11 12 13

In [90]:
3 %in% v

[1] TRUE

In [91]:
v == 3

[1] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [92]:
which(v == 3)

[1] 3

In [93]:
v < 4

[1]  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [94]:
which(v < 4)

[1] 1 2 3

In [95]:
v[v < 4]

[1] 1 2 3

### Matrices

see: https://www.statmethods.net/advstats/matrix.html

In [96]:
v1 = c(1,2,3)
v2 = c(4,5,6)
v3 = c(7,8,9)

mat = matrix( c(v1,v2,v3), ncol=3, nrow=3)
mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [97]:
mat = matrix( c(v1,v2,v3), ncol=3, nrow=3, byrow = F)
mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [98]:
mat = matrix( c(v1,v2,v3), ncol=3, nrow=3, byrow = T)
mat

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [99]:
#-- matrix multiplications
mat %*% mat

[,1] [,2] [,3]
[1,]  30   36   42 
[2,]  66   81   96 
[3,] 102  126  150

In [100]:
#-- determinant
det(mat)

[1] -9.516197e-16

In [101]:
#-- trace !!! there is no function trace !!!
tr <- function(data)sum(diag(data))

tr(mat)

[1] 15

In [102]:
#-- transpose
t(mat)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [103]:
#-- inverse == solve -- why?? and why an error?
solve(mat)

ERROR: Error in solve.default(mat): system is computationally singular: reciprocal condition number = 2.20282e-18


In [104]:
v1 = sample.int(100, 3)
v1

[1] 36 76 74

In [105]:
v2 = sample.int(100, 3)
v3 = sample.int(100, 3)

mat = matrix( c(v1,v2,v3), ncol=3, nrow=3, byrow = T)
mat

[,1] [,2] [,3]
[1,] 36   76   74  
[2,] 87   46   82  
[3,] 46   54   11

In [106]:
#-- aha !!! why?
solve(mat)

[,1]         [,2]         [,3]       
[1,] -0.014866422  0.011978045  0.01071959
[2,]  0.010670316 -0.011401886  0.01321376
[3,]  0.009787124  0.005882888 -0.01878582

### Why always a different result?

because the funciont is random sampler! it is stochastics  

many CTRL+ENTERs

In [107]:
v1 = sample.int(100, 3)
v2 = sample.int(100, 3)
v3 = sample.int(100, 3)

mat = matrix( c(v1,v2,v3), ncol=3, nrow=3, byrow = T)
mat

[,1] [,2] [,3]
[1,] 34   49   63  
[2,] 93   38   74  
[3,] 42   26   58

**How to solve this "problem"?**

In [108]:
# try any seed value - the answer will be always the same
# computer / mathematical functions are false random number generators
set.seed(3)

v1 = sample.int(100, 3)
v2 = sample.int(100, 3)
v3 = sample.int(100, 3)

mat = matrix( c(v1,v2,v3), ncol=3, nrow=3, byrow = T)
mat

[,1] [,2] [,3]
[1,] 17   80   38  
[2,] 33   60   99  
[3,] 13   30   57